# Generated by Django 3.2.25 on 2024-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingrediant'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingrediant',
            field=models.ManyToManyField(to='core.Ingrediant'),
        ),
    ]
